#!/usr/bin/env python3
"""
Keybindings Manager Backend for Omarchy Hyprland

The plugin owns exactly one region at the end of ~/.config/hypr/bindings.lua,
delimited by BLOCK_START / BLOCK_END. That block IS the store: it is parsed
back into records and regenerated in full on every write. Nothing outside the
markers is ever rewritten. Hand-written lines are read (so the model can show
them) but never edited: editing one shadows it from inside the block.

Record = {"id", "description", "key" (chord|None), "action" (verbatim Lua
text), "opts" (verbatim Lua options table|None), "fn" ("o.bind"|
"o.bind_toggle"), "origin_key" (chord the identity holds outside the block,
or None), "last_key" (chord a disabled record had before it was disabled)}.

Identity = description (case-insensitive). Never matched by action text.
"""

import os
import sys
import re
import json
import signal
import select
import stat
import subprocess
import time
from pathlib import Path

DEFAULT_BINDINGS_DIR = os.environ.get("OMARCHY_PATH", "/usr/share/omarchy") + "/default/hypr/bindings"
USER_BINDINGS_PATH = os.path.expanduser("~/.config/hypr/bindings.lua")
CACHE_DIR = os.path.expanduser("~/.cache/omarchy")
# Tests point this at a fake so `hyprctl reload` never runs for real.
HYPRCTL = os.environ.get("OMARCHY_KEYBINDS_HYPRCTL", "hyprctl")

BLOCK_START = "-- [[ OMARCHY_KEYBINDS_START ]]"
BLOCK_END = "-- [[ OMARCHY_KEYBINDS_END ]]"
BLOCK_HEADER = "-- generated by Mouse & Keybind Settings; edit with the plugin, not by hand"
DISABLED_PREFIX = "-- disabled: "
BLOCK_RE = re.compile(re.escape(BLOCK_START) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
NEW_FILE_HEADER = "-- Personal keybinding overrides for Omarchy Hyprland\n"

MODIFIER_ORDER = {"SUPER": 1, "SHIFT": 2, "CTRL": 3, "CONTROL": 3, "ALT": 4}
UNSAFE_KEY_RE = re.compile(r'["\'\\()\n\r\t]')
MAX_KEY_LEN = 64
MAX_TEXT_LEN = 200
MAX_CMD_LEN = 2000
MAX_FILE_BYTES = 65_536
MAX_DIR_FILES = 256
MAX_TOTAL_READ = 2_097_152
MAX_SUBPROCESS_TIMEOUT = 15
MAX_SUBPROCESS_OUTPUT = 1_048_576
MAX_CONTINUATION_LINES = 40


# --------------------------------------------------------------------------
# Subprocess + descriptor-relative file helpers (unchanged security posture)
# --------------------------------------------------------------------------

def run_cmd(cmd) -> tuple:
    """Run a command with:
      - a hard wall-clock timeout,
      - a hard aggregate stdout+stderr byte ceiling enforced *while streaming*
        (not after the process exits), and
      - whole-process-group cleanup (SIGTERM -> SIGKILL + reap) on both
        overflow and timeout, so no child survives.
    Returns (returncode, bounded_stdout, bounded_stderr); on timeout or overflow
    the code is None to signal the failure."""
    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
        )
    except Exception:
        return None, "", ""
    out = bytearray()
    err = bytearray()
    total = 0
    overflow = False
    timed_out = False
    deadline = time.monotonic() + MAX_SUBPROCESS_TIMEOUT
    try:
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                timed_out = True
                break
            fds = [fd for fd in (proc.stdout, proc.stderr) if fd is not None and not fd.closed]
            if not fds:
                break
            rlist, _, _ = select.select(fds, [], [], min(remaining, 0.2))
            for fd in rlist:
                data = os.read(fd.fileno(), 8192)
                if not data:
                    fd.close()
                    continue
                if total + len(data) > MAX_SUBPROCESS_OUTPUT:
                    overflow = True
                    continue
                total += len(data)
                if fd is proc.stdout:
                    out += data
                else:
                    err += data
            if overflow:
                break
        if timed_out or overflow:
            _kill_and_reap(proc)
            return None, _decode(out), _decode(err)
        code = proc.wait()
        return code, _decode(out), _decode(err)
    except Exception:
        _kill_and_reap(proc)
        return None, _decode(out), _decode(err)


def _kill_and_reap(proc):
    try:
        os.killpg(proc.pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        pass
    try:
        proc.wait(timeout=2)
        return
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(proc.pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError, OSError):
        pass
    try:
        proc.wait(timeout=2)
    except subprocess.TimeoutExpired:
        try:
            proc.wait()
        except Exception:
            pass


def _decode(data: bytearray) -> str:
    return bytes(data).decode("utf-8", errors="replace").strip()


def _parent_dir_fd(path):
    """Open path's parent directory via component-wise descriptor-relative
    traversal: every component is opened with openat(..., O_DIRECTORY|O_NOFOLLOW)
    relative to the previously retained dirfd, walking from '/'. No pathname is
    ever followed, so a symlink substitution at any ancestor is rejected."""
    p = Path(path)
    if not p.is_absolute():
        raise ValueError(f"expected absolute path: {path}")
    parent = p.parent
    comps = parent.parts[1:]  # drop the leading root component
    fd = os.open("/", os.O_RDONLY | os.O_DIRECTORY)
    try:
        for comp in comps:
            nfd = os.open(comp, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=fd)
            os.close(fd)
            fd = nfd
            if not stat.S_ISDIR(os.fstat(fd).st_mode):
                raise ValueError(f"refusing non-directory component: {comp}")
        return fd
    except FileNotFoundError:
        os.close(fd)
        raise
    except OSError as e:
        os.close(fd)
        raise ValueError(f"cannot traverse path: {path} ({e})") from e
    except BaseException:
        os.close(fd)
        raise


def _open_dir_fd(path):
    """Open path itself as a directory via descriptor-relative O_NOFOLLOW walk.
    Raises FileNotFoundError if the directory is absent and ValueError on any
    unsafe component."""
    p = Path(path)
    comps = p.parts[1:]
    fd = os.open("/", os.O_RDONLY | os.O_DIRECTORY)
    try:
        for comp in comps:
            nfd = os.open(comp, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=fd)
            os.close(fd)
            fd = nfd
            if not stat.S_ISDIR(os.fstat(fd).st_mode):
                raise ValueError(f"refusing non-directory component: {comp}")
        return fd
    except FileNotFoundError:
        os.close(fd)
        raise
    except OSError as e:
        os.close(fd)
        raise ValueError(f"cannot open directory safely: {path} ({e})") from e
    except BaseException:
        os.close(fd)
        raise


def safe_open_config(path, *, owner_check=True, max_bytes=MAX_FILE_BYTES):
    """Open a config file relative to its descriptor-verified parent dirfd with
    no-follow, regular-file and (optionally) owner checks, returning
    (fd, size). Raises FileNotFoundError when genuinely absent and ValueError
    on unsafe conditions."""
    p = Path(path)
    parent_fd = _parent_dir_fd(path)
    try:
        try:
            fd = os.open(p.name, os.O_RDONLY | os.O_NOFOLLOW, dir_fd=parent_fd)
        except FileNotFoundError:
            raise
        except IsADirectoryError:
            raise ValueError(f"refusing directory where file expected: {path}")
        except OSError as e:
            raise ValueError(f"refusing non-regular/symlink path: {path} ({e})") from e
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            os.close(fd)
            raise ValueError(f"refusing non-regular file: {path}")
        if owner_check and st.st_uid != os.geteuid():
            os.close(fd)
            raise ValueError(f"refusing file not owned by user: {path}")
        if st.st_size > max_bytes:
            os.close(fd)
            raise ValueError(f"refusing oversized config file: {path}")
        return fd, st.st_size
    finally:
        os.close(parent_fd)


def _read_fd_capped(fd, max_bytes):
    """Read up to max_bytes+1 from the current fd offset, raising ValueError
    (cap+1 overflow rejection) if the file exceeds the limit."""
    raw = os.read(fd, max_bytes + 1)
    if len(raw) > max_bytes:
        raise ValueError("config file exceeds size limit")
    return raw.decode("utf-8")


def _atomic_write(path, data: bytes, mode):
    """tmp + fsync + os.replace, all relative to the verified parent dirfd."""
    name = Path(path).name
    parent_fd = _parent_dir_fd(path)
    try:
        tmp_name = f".{name}.{os.getpid()}.{os.urandom(4).hex()}.tmp"
        tmp_fd = os.open(tmp_name, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode, dir_fd=parent_fd)
        try:
            wrote = 0
            while wrote < len(data):
                wrote += os.write(tmp_fd, data[wrote:])
            os.fsync(tmp_fd)
            os.close(tmp_fd)
            tmp_fd = -1
            os.replace(tmp_name, name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        except BaseException:
            try:
                if tmp_fd != -1:
                    os.close(tmp_fd)
            except OSError:
                pass
            try:
                os.unlink(tmp_name, dir_fd=parent_fd)
            except OSError:
                pass
            raise
    finally:
        os.close(parent_fd)


# --------------------------------------------------------------------------
# Lua text helpers
# --------------------------------------------------------------------------

def sanitize_lua_str(s: str) -> str:
    s = (s or "").replace("\r", " ").replace("\n", " ")
    if len(s) > MAX_TEXT_LEN:
        s = s[:MAX_TEXT_LEN]
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _scan_code(line: str):
    """Split a Lua line into (code, comment) at the first `--` outside a
    string literal. comment is "" when there is none."""
    in_str = None
    esc = False
    i = 0
    while i < len(line):
        ch = line[i]
        if esc:
            esc = False
        elif in_str:
            if ch == "\\":
                esc = True
            elif ch == in_str:
                in_str = None
        else:
            if ch == '"' or ch == "'":
                in_str = ch
            elif ch == "-" and line.startswith("--", i):
                return line[:i].rstrip(), line[i + 2:].strip()
        i += 1
    return line.rstrip(), ""


def _paren_depth(code: str) -> int:
    depth = 0
    in_str = None
    esc = False
    for ch in code:
        if esc:
            esc = False
            continue
        if in_str:
            if ch == "\\":
                esc = True
            elif ch == in_str:
                in_str = None
            continue
        if ch == '"' or ch == "'":
            in_str = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
    return depth


_STMT_START_RE = re.compile(r"^(?:o\.bind(?:_toggle)?|hl\.unbind)\s*\(")
_UNBIND_RE = re.compile(r'^hl\.unbind\s*\(\s*["\']([^"\']+)["\']\s*\)\s*$')
_BIND_HEADER_RE = re.compile(
    r"(o\.bind(?:_toggle)?)\s*\(\s*[\"']([^\"']+)[\"']\s*,\s*"
    r"(?:[\"']([^\"']+)[\"']|nil)\s*,\s*"
)


def iter_statements(text: str, first_line: int = 1, allow_disabled: bool = False):
    """Yield top-level o.bind / o.bind_toggle / hl.unbind statements found in
    text. Continuation lines are joined until the parentheses balance, so
    multi-line calls get their full action. Loop forms such as
    o.bind("SUPER + " .. key, ...) and hl.bind(...) are simply skipped by the
    later parse step. Yields dicts {line, code, comment, disabled}."""
    lines = text.split("\n")
    n = len(lines)
    i = 0
    while i < n:
        s = lines[i].strip()
        disabled = False
        if allow_disabled and s.startswith(DISABLED_PREFIX.strip()):
            s = s[len(DISABLED_PREFIX.strip()):].strip()
            disabled = True
        if not s or s.startswith("--") or not _STMT_START_RE.match(s):
            i += 1
            continue
        code, comment = _scan_code(s)
        j = i
        depth = _paren_depth(code)
        while depth > 0 and j + 1 < n and (j - i) < MAX_CONTINUATION_LINES:
            j += 1
            c2, cm2 = _scan_code(lines[j].strip())
            if c2:
                code = code + " " + c2
            if cm2 and not comment:
                comment = cm2
            depth = _paren_depth(code)
        if depth == 0:
            yield {"line": first_line + i, "end_line": first_line + j, "code": code.strip(),
                   "comment": comment, "disabled": disabled}
        i = j + 1


def _parse_bind_line(line: str):
    """Parse one (already joined) o.bind/o.bind_toggle call. Returns
    (raw_key, description, action_text, opts_text|None) or None."""
    m = _BIND_HEADER_RE.match(line)
    if not m:
        return None
    raw_key = m.group(2).strip()
    desc = (m.group(3) or "").strip()
    pos = m.end()
    depth_paren = 0
    depth_brace = 0
    in_string = None
    escape_next = False
    action_start = pos
    while pos < len(line):
        ch = line[pos]
        if escape_next:
            escape_next = False
            pos += 1
            continue
        if ch == '\\' and in_string:
            escape_next = True
            pos += 1
            continue
        if ch == '"' or ch == "'":
            if not in_string:
                in_string = ch
            elif in_string == ch:
                in_string = None
            pos += 1
            continue
        if in_string:
            pos += 1
            continue
        if ch == '(':
            depth_paren += 1
        elif ch == ')':
            if depth_paren > 0:
                depth_paren -= 1
            else:
                break
        elif ch == '{':
            depth_brace += 1
        elif ch == '}':
            depth_brace -= 1
        elif ch == ',' and depth_paren == 0 and depth_brace == 0:
            break
        pos += 1
    action = line[action_start:pos].strip()
    opts = None
    if pos < len(line) and line[pos] == ',':
        opts_text = line[pos + 1:].rstrip()
        if opts_text.endswith(')'):
            opts_text = opts_text[:-1].strip()
        if opts_text:
            opts = opts_text
    return raw_key, desc, action, opts


def _is_release(opts):
    return bool(opts) and bool(re.search(r"\b(?:on_)?release\s*=\s*true", opts))


def _is_mouse(raw_key, opts):
    return "mouse" in (raw_key or "").lower() or bool(opts and re.search(r"\bmouse\s*=\s*true", opts))


def parse_statement(code: str):
    """Turn a joined statement into {"kind": "unbind", "key"} or
    {"kind": "bind", ...}. None for anything we do not understand (loop
    forms, hl.bind, ...)."""
    m = _UNBIND_RE.match(code)
    if m:
        key = normalize_key_chord(m.group(1))
        if not key:
            return None
        return {"kind": "unbind", "key": key, "raw_key": m.group(1).strip()}
    parsed = _parse_bind_line(code)
    if not parsed:
        return None
    raw_key, desc, action, opts = parsed
    key = normalize_key_chord(raw_key)
    if not key:
        return None
    fn = _BIND_HEADER_RE.match(code).group(1)
    return {
        "kind": "bind",
        "fn": fn,
        "key": key,
        "raw_key": raw_key,
        "description": desc or action.strip('"\''),
        "action": action,
        "opts": opts,
        "is_mouse": _is_mouse(raw_key, opts),
        "is_release": _is_release(opts),
    }


def _make_id(desc: str) -> str:
    return re.sub(r"\s+", " ", (desc or "").strip()).lower()


def _assign_ids(entries):
    """Identity = description (case-insensitive). When one source declares the
    same description twice (stock does: "Next track", "Reveal active window on
    top", ...), later occurrences get an "@<chord>" suffix so ids stay unique."""
    ids = set()
    for e in entries:
        base = _make_id(e.get("description")) or _make_id(e.get("action"))
        cand = base
        if cand in ids:
            cand = f"{base}@{e['key']}"
            n = 2
            while cand in ids:
                cand = f"{base}@{e['key']}#{n}"
                n += 1
        e["id"] = cand
        ids.add(cand)
    return entries


def _command_from_action(action: str) -> str:
    a = (action or "").strip()
    if len(a) >= 2 and a[0] == a[-1] and a[0] in "\"'":
        return a[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return a


def _build_action(command: str, action: str = "") -> str:
    """Turn the CLI's (command, action) pair into verbatim Lua action text."""
    for cand in (action, command):
        c = (cand or "").strip().replace("\r", " ").replace("\n", " ")
        if c.startswith("{") or c.startswith("hl.") or c.startswith("function"):
            return c[:MAX_CMD_LEN]
    raw = (command or action or "").strip()
    if (raw.startswith('"') and raw.endswith('"')) or (raw.startswith("'") and raw.endswith("'")):
        raw = raw[1:-1]
    return '"' + sanitize_lua_str(raw[:MAX_CMD_LEN]) + '"'


# --------------------------------------------------------------------------
# Preset catalog (unchanged)
# --------------------------------------------------------------------------

PRESET_CATALOG = [
    {"id": "win.close", "category": "Window Management", "name": "Close Window", "description": "Close currently focused window", "dispatcher": "hl.dsp.window.close()", "command": "hyprctl dispatch killactive", "default_key": "SUPER + W"},
    {"id": "win.close_all", "category": "Window Management", "name": "Close All Windows", "description": "Close all open windows on current workspace", "dispatcher": "exec", "command": "omarchy-hyprland-window-close-all", "default_key": "CTRL + ALT + DELETE"},
    {"id": "win.fullscreen", "category": "Window Management", "name": "Toggle Fullscreen", "description": "Toggle fullscreen state for focused window", "dispatcher": "hl.dsp.window.fullscreen()", "command": "hyprctl dispatch fullscreen", "default_key": "SUPER + F"},
    {"id": "win.fullwidth", "category": "Window Management", "name": "Toggle Full Width", "description": "Expand window across the full screen width", "dispatcher": "hl.dsp.window.fullwidth()", "command": "hyprctl dispatch fullscreen 2", "default_key": "SUPER + ALT + F"},
    {"id": "win.floating", "category": "Window Management", "name": "Toggle Window Floating", "description": "Toggle between tiling and floating mode", "dispatcher": "hl.dsp.window.float({ action = \"toggle\" })", "command": "hyprctl dispatch togglefloating", "default_key": "SUPER + T"},
    {"id": "win.split", "category": "Window Management", "name": "Toggle Split Direction", "description": "Toggle window tiling split between horizontal/vertical", "dispatcher": "hl.dsp.layout(\"togglesplit\")", "command": "hyprctl dispatch layoutmsg togglesplit", "default_key": "SUPER + J"},
    {"id": "win.popout", "category": "Window Management", "name": "Pop Window Out (Float & Pin)", "description": "Float focused window and pin it across workspaces", "dispatcher": "exec", "command": "omarchy-hyprland-window-pop", "default_key": "SUPER + O"},
    {"id": "win.transparency", "category": "Window Management", "name": "Toggle Window Transparency", "description": "Toggle transparency for active window", "dispatcher": "exec", "command": "omarchy-hyprland-window-transparency-toggle", "default_key": "SUPER + BACKSPACE"},
    {"id": "win.gaps", "category": "Window Management", "name": "Toggle Window Gaps", "description": "Toggle inner and outer workspace window gaps", "dispatcher": "exec", "command": "omarchy-hyprland-window-gaps-toggle", "default_key": "SUPER + SHIFT + BACKSPACE"},
    {"id": "win.focus_left", "category": "Window Management", "name": "Focus Window Left", "description": "Move focus to the window on the left", "dispatcher": "hl.dsp.focus.left()", "command": "hyprctl dispatch movefocus l", "default_key": "SUPER + LEFT"},
    {"id": "win.focus_right", "category": "Window Management", "name": "Focus Window Right", "description": "Move focus to the window on the right", "dispatcher": "hl.dsp.focus.right()", "command": "hyprctl dispatch movefocus r", "default_key": "SUPER + RIGHT"},
    {"id": "win.focus_up", "category": "Window Management", "name": "Focus Window Up", "description": "Move focus to the window above", "dispatcher": "hl.dsp.focus.up()", "command": "hyprctl dispatch movefocus u", "default_key": "SUPER + UP"},
    {"id": "win.focus_down", "category": "Window Management", "name": "Focus Window Down", "description": "Move focus to the window below", "dispatcher": "hl.dsp.focus.down()", "command": "hyprctl dispatch movefocus d", "default_key": "SUPER + DOWN"},
    {"id": "win.move_left", "category": "Window Management", "name": "Move Window Left", "description": "Move active window to the left in tiling layout", "dispatcher": "hl.dsp.window.move({ direction = \"left\" })", "command": "hyprctl dispatch movewindow l", "default_key": "SUPER + SHIFT + LEFT"},
    {"id": "win.move_right", "category": "Window Management", "name": "Move Window Right", "description": "Move active window to the right in tiling layout", "dispatcher": "hl.dsp.window.move({ direction = \"right\" })", "command": "hyprctl dispatch movewindow r", "default_key": "SUPER + SHIFT + RIGHT"},
    {"id": "win.move_up", "category": "Window Management", "name": "Move Window Up", "description": "Move active window up in tiling layout", "dispatcher": "hl.dsp.window.move({ direction = \"up\" })", "command": "hyprctl dispatch movewindow u", "default_key": "SUPER + SHIFT + UP"},
    {"id": "win.move_down", "category": "Window Management", "name": "Move Window Down", "description": "Move active window down in tiling layout", "dispatcher": "hl.dsp.window.move({ direction = \"down\" })", "command": "hyprctl dispatch movewindow d", "default_key": "SUPER + SHIFT + DOWN"},
    {"id": "ws.next", "category": "Workspaces", "name": "Next Workspace", "description": "Switch to next workspace", "dispatcher": "hl.dsp.focus({ workspace = \"e+1\" })", "command": "hyprctl dispatch workspace e+1", "default_key": "SUPER + TAB"},
    {"id": "ws.prev", "category": "Workspaces", "name": "Previous Workspace", "description": "Switch to previous workspace", "dispatcher": "hl.dsp.focus({ workspace = \"e-1\" })", "command": "hyprctl dispatch workspace e-1", "default_key": "SUPER + SHIFT + TAB"},
    {"id": "ws.scratchpad_toggle", "category": "Workspaces", "name": "Toggle Special Scratchpad", "description": "Toggle overlay special workspace (scratchpad)", "dispatcher": "hl.dsp.special_workspace.focus({ name = \"scratchpad\" })", "command": "hyprctl dispatch togglespecialworkspace scratchpad", "default_key": "SUPER + S"},
    {"id": "ws.scratchpad_moveto", "category": "Workspaces", "name": "Move to Scratchpad", "description": "Move focused window into special scratchpad", "dispatcher": "hl.dsp.special_workspace.move_window({ name = \"scratchpad\" })", "command": "hyprctl dispatch movetoworkspace special:scratchpad", "default_key": "SUPER + ALT + S"},
    {"id": "menu.root", "category": "Menus & System", "name": "Omarchy Menu", "description": "Summon the primary Omarchy launcher menu", "dispatcher": "exec", "command": "omarchy-menu toggle", "default_key": "SUPER + SPACE"},
    {"id": "menu.apps", "category": "Menus & System", "name": "Apps Menu", "description": "Summon the applications list menu", "dispatcher": "exec", "command": "omarchy-menu toggle apps", "default_key": "SUPER + ALT + SPACE"},
    {"id": "menu.system", "category": "Menus & System", "name": "System / Power Menu", "description": "Summon the system power/logout menu", "dispatcher": "exec", "command": "omarchy-menu toggle system", "default_key": "SUPER + ESCAPE"},
    {"id": "menu.keybindings", "category": "Menus & System", "name": "Keybindings Helper", "description": "Open keybindings quick selector", "dispatcher": "exec", "command": "omarchy-menu-keybindings", "default_key": "SUPER + K"},
    {"id": "shell.emojis", "category": "Menus & System", "name": "Emoji Picker", "description": "Open full-screen emoji selector overlay", "dispatcher": "exec", "command": "omarchy-shell shell toggle omarchy.emojis", "default_key": "SUPER + CTRL + E"},
    {"id": "shell.clipboard", "category": "Menus & System", "name": "Clipboard Manager", "description": "Open clipboard history overlay", "dispatcher": "exec", "command": "omarchy-shell shell toggle omarchy.clipboard", "default_key": "SUPER + CTRL + V"},
    {"id": "shell.theme", "category": "Menus & System", "name": "Theme Menu", "description": "Summon the Omarchy theme switcher", "dispatcher": "exec", "command": "omarchy-menu toggle theme", "default_key": "SUPER + SHIFT + CTRL + SPACE"},
    {"id": "shell.background", "category": "Menus & System", "name": "Background Switcher", "description": "Summon wallpaper selector overlay", "dispatcher": "exec", "command": "omarchy-menu toggle background", "default_key": "SUPER + CTRL + SPACE"},
    {"id": "shell.toggle_bar", "category": "Menus & System", "name": "Toggle Menu Bar", "description": "Show or hide the top status bar", "dispatcher": "exec", "command": "omarchy-toggle-bar", "default_key": "SUPER + SHIFT + SPACE"},
    {"id": "sys.lock", "category": "Menus & System", "name": "Lock System", "description": "Trigger session screen lock", "dispatcher": "exec", "command": "omarchy-system-lock", "default_key": "SUPER + CTRL + L"},
    {"id": "sys.screensaver", "category": "Menus & System", "name": "Screensaver", "description": "Start the Omarchy screensaver", "dispatcher": "exec", "command": "omarchy-launch-screensaver force", "default_key": "SUPER + ALT + L"},
    {"id": "app.terminal", "category": "Applications", "name": "Terminal", "description": "Terminal", "dispatcher": "{ omarchy = \"terminal\" }", "command": "omarchy-launch-terminal", "default_key": "SUPER + RETURN"},
    {"id": "app.browser", "category": "Applications", "name": "Browser", "description": "Browser", "dispatcher": "{ omarchy = \"browser\" }", "command": "omarchy-launch-browser", "default_key": "SUPER + SHIFT + RETURN"},
    {"id": "app.file_manager", "category": "Applications", "name": "File Manager", "description": "File manager", "dispatcher": "{ omarchy = \"nautilus\" }", "command": "omarchy-launch-nautilus", "default_key": "SUPER + SHIFT + F"},
    {"id": "app.file_manager_cwd", "category": "Applications", "name": "File Manager (Active CWD)", "description": "File manager (cwd)", "dispatcher": "{ omarchy = \"nautilus-cwd\" }", "command": "omarchy-launch-nautilus-cwd", "default_key": "SUPER + ALT + SHIFT + F"},
    {"id": "app.editor", "category": "Applications", "name": "Code Editor", "description": "Editor", "dispatcher": "{ omarchy = \"editor\" }", "command": "omarchy-launch-editor", "default_key": "SUPER + SHIFT + N"},
    {"id": "app.docker", "category": "Applications", "name": "Docker", "description": "Docker", "dispatcher": "{ tui = \"lazydocker\" }", "command": "lazydocker", "default_key": "SUPER + SHIFT + D"},
    {"id": "app.calculator", "category": "Applications", "name": "Calculator", "description": "Calculator", "dispatcher": "exec", "command": "omacalc", "default_key": "SUPER + CTRL + Q"},
    {"id": "media.volume_up", "category": "Media & Audio", "name": "Volume Up", "description": "Raise audio output volume", "dispatcher": "exec", "command": "omarchy-audio-output-volume raise", "default_key": "XF86AudioRaiseVolume"},
    {"id": "media.volume_down", "category": "Media & Audio", "name": "Volume Down", "description": "Lower audio output volume", "dispatcher": "exec", "command": "omarchy-audio-output-volume lower", "default_key": "XF86AudioLowerVolume"},
    {"id": "media.mute", "category": "Media & Audio", "name": "Mute Audio", "description": "Toggle audio output mute", "dispatcher": "exec", "command": "omarchy-audio-output-volume mute-toggle", "default_key": "XF86AudioMute"},
    {"id": "media.mic_mute", "category": "Media & Audio", "name": "Mute Microphone", "description": "Toggle audio microphone mute", "dispatcher": "exec", "command": "omarchy-audio-input-mute", "default_key": "XF86AudioMicMute"},
    {"id": "media.screenshot", "category": "Media & Audio", "name": "Capture Screenshot", "description": "Capture screen or interactive slurp region", "dispatcher": "exec", "command": "omarchy-capture-screenshot", "default_key": "PRINT"},
    {"id": "media.screenrecord", "category": "Media & Audio", "name": "Toggle Screenrecording", "description": "Start or stop screenrecording", "dispatcher": "exec", "command": "omarchy-capture-screenrecording --stop-recording || omarchy-menu toggle trigger.capture.screenrecord", "default_key": "ALT + PRINT"},
    {"id": "media.color_picker", "category": "Media & Audio", "name": "Color Picker", "description": "Pick color under cursor to clipboard", "dispatcher": "exec", "command": "pkill hyprpicker || hyprpicker -a", "default_key": "SUPER + PRINT"},
    {"id": "media.ocr_text", "category": "Media & Audio", "name": "OCR Text from Screen", "description": "Extract text from selected screen area", "dispatcher": "exec", "command": "omarchy-capture-text", "default_key": "SUPER + CTRL + PRINT"},
]


def normalize_key_chord(key_chord: str) -> str:
    if not key_chord:
        return ""
    raw_parts = [p.strip() for p in key_chord.replace(",", "+").split("+") if p.strip()]
    if not raw_parts:
        return ""
    mods = []
    main_key = ""
    for part in raw_parts:
        upper = part.upper()
        if upper in ("SUPER", "WIN", "LOGO", "SUPER_L", "SUPER_R", "META", "MOD4"):
            if "SUPER" not in mods:
                mods.append("SUPER")
        elif upper in ("SHIFT", "SHIFT_L", "SHIFT_R"):
            if "SHIFT" not in mods:
                mods.append("SHIFT")
        elif upper in ("CTRL", "CONTROL", "CONTROL_L", "CONTROL_R"):
            if "CTRL" not in mods:
                mods.append("CTRL")
        elif upper in ("ALT", "ALT_L", "ALT_R", "MOD1"):
            if "ALT" not in mods:
                mods.append("ALT")
        else:
            main_key = part
    mods.sort(key=lambda m: MODIFIER_ORDER.get(m, 99))
    if main_key:
        upper_k = main_key.upper()
        if upper_k in ("RETURN", "ENTER", "SPACE", "ESCAPE", "TAB", "BACKSPACE", "DELETE", "PRINT"):
            main_key = upper_k
        elif upper_k in ("LEFT", "RIGHT", "UP", "DOWN"):
            main_key = upper_k
        elif upper_k.startswith("F") and upper_k[1:].isdigit():
            main_key = upper_k
        elif main_key in ("comma", "period", "slash", "minus", "equal", "bracketleft", "bracketright", "semicolon", "apostrophe", "backslash"):
            pass
        elif len(main_key) == 1:
            main_key = main_key.upper()
    if mods and main_key:
        out = f"{' + '.join(mods)} + {main_key}"
    elif mods and not main_key:
        out = " + ".join(mods)
    else:
        out = main_key
    if len(out) > MAX_KEY_LEN or UNSAFE_KEY_RE.search(out or ""):
        return ""
    return out


def get_mouse_scroll_settings():
    settings = {"natural_scroll": False, "scroll_factor": 1.0}
    try:
        code, outp, _ = run_cmd([HYPRCTL, "getoption", "input:scroll_factor", "-j"])
        if code == 0 and outp:
            data = json.loads(outp)
            if "float" in data:
                settings["scroll_factor"] = float(data["float"])
    except Exception:
        pass
    try:
        code, outp, _ = run_cmd([HYPRCTL, "getoption", "input:natural_scroll", "-j"])
        if code == 0 and outp:
            data = json.loads(outp)
            if "bool" in data:
                settings["natural_scroll"] = bool(data["bool"])
    except Exception:
        pass
    return settings


# --------------------------------------------------------------------------
# Parsing: stock bindings and the user file
# --------------------------------------------------------------------------

_CATEGORY_BY_FILE = {
    "applications": "Applications",
    "tiling": "Window Management",
    "media": "Media & Audio",
    "utilities": "Menus & System",
    "clipboard": "Clipboard",
    "voxtype": "AI & Voice",
}


def parse_default_bindings():
    """Stock binds from $OMARCHY_PATH/default/hypr/bindings/*.lua."""
    bindings = []
    try:
        dirfd = _open_dir_fd(DEFAULT_BINDINGS_DIR)
    except (FileNotFoundError, ValueError):
        return bindings
    try:
        names = sorted(e.name for e in os.scandir(dirfd))
        file_count = 0
        total_read = 0
        for fname in names:
            if file_count >= MAX_DIR_FILES or total_read > MAX_TOTAL_READ:
                break
            file_count += 1
            if not fname.endswith(".lua"):
                continue
            try:
                src_fd = os.open(fname, os.O_RDONLY | os.O_NOFOLLOW, dir_fd=dirfd)
            except OSError:
                continue
            try:
                st = os.fstat(src_fd)
                if not stat.S_ISREG(st.st_mode) or st.st_size > MAX_FILE_BYTES:
                    continue
                content = _read_fd_capped(src_fd, MAX_FILE_BYTES)
            except Exception:
                continue
            finally:
                os.close(src_fd)
            total_read += len(content.encode("utf-8"))
            cat = _CATEGORY_BY_FILE.get(fname[:-4], "General")
            for st_ in iter_statements(content):
                p = parse_statement(st_["code"])
                if not p or p["kind"] != "bind":
                    continue
                bindings.append({
                    "source": "default",
                    "file": fname,
                    "line": st_["line"],
                    "key": p["key"],
                    "raw_key": p["raw_key"],
                    "description": p["description"],
                    "action": p["action"],
                    "opts": p["opts"],
                    "fn": p["fn"],
                    "category": cat,
                    "is_mouse": p["is_mouse"],
                    "is_release": p["is_release"],
                })
    finally:
        os.close(dirfd)
    return _assign_ids(bindings)


def parse_user_file(path=None):
    """Read the user file once. Returns {exists, content, mode, block (text or
    None), block_span ((start, end) or None), binds, unbinds} where binds and
    unbinds are the hand-written statements OUTSIDE the managed block."""
    path = path or USER_BINDINGS_PATH
    result = {"exists": False, "content": "", "mode": 0o644, "block": None,
              "block_span": None, "binds": [], "unbinds": []}
    try:
        src_fd, _ = safe_open_config(path, owner_check=True)
    except FileNotFoundError:
        return result
    try:
        content = _read_fd_capped(src_fd, MAX_FILE_BYTES)
        result["mode"] = stat.S_IMODE(os.fstat(src_fd).st_mode)
    finally:
        os.close(src_fd)
    result["exists"] = True
    result["content"] = content
    outside = content
    m = BLOCK_RE.search(content)
    if m:
        result["block"] = m.group(0)
        result["block_span"] = (m.start(), m.end())
        outside = content[:m.start()] + ("\n" * m.group(0).count("\n")) + content[m.end():]
    for st_ in iter_statements(outside):
        p = parse_statement(st_["code"])
        if not p:
            continue
        p["line"] = st_["line"]
        p["end_line"] = st_["end_line"]
        if p["kind"] == "unbind":
            result["unbinds"].append(p)
        else:
            result["binds"].append(p)
    return result


def parse_user_bindings():
    """Backward-compatible view of the hand-written part of the user file."""
    uf = parse_user_file()
    binds = []
    mouse = []
    for b in uf["binds"]:
        entry = {
            "source": "user",
            "key": b["key"],
            "raw_key": b["raw_key"],
            "description": b["description"],
            "action": b["action"],
            "is_mouse": b["is_mouse"],
            "is_release": b["is_release"],
            "line": b["line"],
        }
        (mouse if b["is_mouse"] else binds).append(entry)
    return {
        "raw_content": uf["content"],
        "unbinds": {u["key"] for u in uf["unbinds"]},
        "binds": binds,
        "mouse_binds": mouse,
    }


# --------------------------------------------------------------------------
# Context: read-only view of stock + hand-written state, and the base rows
# --------------------------------------------------------------------------

def _new_row(**kw):
    row = {
        "id": "", "key": None, "description": "", "action": "", "command": "", "opts": None,
        "fn": "o.bind", "category": "Custom", "status": "custom", "source": "default",
        "managed": False, "default_key": "", "default_action": "", "stock_key": "",
        "origin_key": None, "last_key": None, "is_conflict": False, "conflict_with": [],
        "file_line": None, "file": None, "is_mouse": False, "is_release": False,
    }
    row.update(kw)
    row["command"] = _command_from_action(row["action"])
    return row


class Context:
    def __init__(self, stock, user):
        self.stock = stock
        self.user = user
        self.content = user["content"]
        self.mode = user["mode"]
        self.block = user["block"]
        self.block_span = user["block_span"]
        self.stock_chords = {s["key"] for s in stock if s["key"]}
        self.user_bind_chords = {b["key"] for b in user["binds"] if b["key"]}
        self.base = self._build_base_rows()

    def unmanaged_holds(self, key) -> bool:
        """True when a bind outside the block (stock or hand-written) declares
        this chord, so a managed bind on it needs a preceding hl.unbind."""
        return bool(key) and (key in self.stock_chords or key in self.user_bind_chords)

    def _build_base_rows(self):
        rows = {}
        for s in self.stock:
            rows[s["id"]] = _new_row(
                id=s["id"], key=s["key"], description=s["description"], action=s["action"],
                opts=s["opts"], fn=s["fn"], category=s["category"], status="default",
                source="default", default_key=s["key"], default_action=s["action"],
                stock_key=s["key"], origin_key=s["key"], file=s["file"],
                is_mouse=s["is_mouse"], is_release=s["is_release"],
            )
        unbound = {}
        for ub in self.user["unbinds"]:
            unbound.setdefault(ub["key"], ub["line"])
        for row in rows.values():
            if row["key"] in unbound:
                row.update(key=None, status="disabled", source="user-file",
                           file_line=unbound[row["key"]], last_key=row["stock_key"])
        user_binds = _assign_ids([dict(b) for b in self.user["binds"]])
        for hb in user_binds:
            base = rows.get(hb["id"])
            if base is not None and not base.get("_hand_written"):
                base.update(
                    key=hb["key"], description=hb["description"], action=hb["action"],
                    opts=hb["opts"], fn=hb["fn"], source="user-file", managed=False,
                    file_line=hb["line"], origin_key=hb["key"], last_key=None,
                    is_mouse=hb["is_mouse"], is_release=hb["is_release"], _hand_written=True,
                )
                base["command"] = _command_from_action(base["action"])
                base["status"] = "modified" if (
                    base["key"] != base["default_key"] or base["action"] != base["default_action"]
                ) else "default"
            else:
                rid = hb["id"]
                if rid in rows:
                    rid = f"{rid}@{hb['key']}"
                rows[rid] = _new_row(
                    id=rid, key=hb["key"], description=hb["description"], action=hb["action"],
                    opts=hb["opts"], fn=hb["fn"], category="Custom", status="custom",
                    source="user-file", origin_key=hb["key"], file_line=hb["line"],
                    is_mouse=hb["is_mouse"], is_release=hb["is_release"], _hand_written=True,
                )
        return rows

    def origin_for(self, rid):
        """Chord the identity holds outside the block (None when nothing
        outside the block binds it, e.g. custom or hand-unbound stock)."""
        base = self.base.get(rid)
        return base["key"] if base else None


def load_context():
    return Context(parse_default_bindings(), parse_user_file())


# --------------------------------------------------------------------------
# Records: the managed block parsed back, and regenerated
# --------------------------------------------------------------------------

_ID_COMMENT_RE = re.compile(r"^id:\s*(.+?)\s*(?:;\s*was\s+.+)?$")


def _comment_id(comment):
    if not comment:
        return None
    m = _ID_COMMENT_RE.match(comment.strip())
    return m.group(1) if m else None


def _records_from_statements(stmts, ctx):
    """Records from parsed statements. A bind = an active record (or a disabled
    one when it came from a `-- disabled:` line). An unbind of a chord that
    some unmanaged bind still declares, with no managed bind of that identity,
    = an implicit disabled record for that identity."""
    records = {}
    unbind_chords = []
    for st_ in stmts:
        p = parse_statement(st_["code"])
        if not p:
            continue
        if p["kind"] == "unbind":
            unbind_chords.append(p["key"])
            continue
        rid = _comment_id(st_.get("comment")) or _make_id(p["description"])
        rec = {
            "id": rid,
            "description": p["description"],
            "key": None if st_.get("disabled") else p["key"],
            "last_key": p["key"] if st_.get("disabled") else None,
            "action": p["action"],
            "opts": p["opts"],
            "fn": p["fn"],
            "origin_key": ctx.origin_for(rid),
        }
        prev = records.get(rid)
        if prev is None or (prev["key"] is None and rec["key"] is not None):
            records[rid] = rec
    for chord in unbind_chords:
        for row in ctx.base.values():
            if row["key"] == chord and row["id"] not in records:
                records[row["id"]] = {
                    "id": row["id"], "description": row["description"], "key": None,
                    "last_key": chord, "action": row["action"], "opts": row["opts"],
                    "fn": row["fn"], "origin_key": chord,
                }
    return list(records.values())


def load_records(block_text, ctx):
    if not block_text:
        return []
    return _records_from_statements(list(iter_statements(block_text, allow_disabled=True)), ctx)


def _collect_unbinds(records, ctx):
    unbinds = []

    def add(k):
        if k and k not in unbinds:
            unbinds.append(k)

    for r in sorted(records, key=lambda r: r["id"]):
        if r["key"] is None:
            add(r.get("origin_key"))
        else:
            if r.get("origin_key") and r["origin_key"] != r["key"]:
                add(r["origin_key"])
            if ctx.unmanaged_holds(r["key"]):
                add(r["key"])
    return unbinds


def _format_bind(r, key=None):
    key = key or r["key"]
    desc = sanitize_lua_str(r["description"])
    action = (r.get("action") or '""').replace("\r", " ").replace("\n", " ")
    s = f'{r.get("fn") or "o.bind"}("{key}", "{desc}", {action}'
    if r.get("opts"):
        s += f', {r["opts"]}'
    s += ")"
    comments = []
    if _make_id(r["description"]) != r["id"]:
        comments.append(f"id: {r['id']}")
    if r.get("origin_key") and r["origin_key"] != key:
        comments.append(f"was {r['origin_key']}")
    if comments:
        s += " -- " + "; ".join(comments)
    return s


def render_block(records, ctx):
    """The whole managed block: all unbinds first (deduped), then binds, then
    disabled records as commented binds; stable order by id."""
    recs = sorted(records, key=lambda r: r["id"])
    lines = [BLOCK_START, BLOCK_HEADER]
    lines += [f'hl.unbind("{k}")' for k in _collect_unbinds(recs, ctx)]
    for r in recs:
        if r["key"]:
            lines.append(_format_bind(r))
    for r in recs:
        if not r["key"]:
            k = r.get("last_key") or r.get("origin_key")
            if k:
                lines.append(DISABLED_PREFIX + _format_bind(r, key=k))
    lines.append(BLOCK_END)
    return "\n".join(lines)


def render_file(ctx, records):
    """Replace-or-append the managed block; nothing outside it is touched.
    With no records left, the block is removed entirely."""
    content = ctx.content
    block = render_block(records, ctx) if records else None
    if ctx.block_span:
        s, e = ctx.block_span
        if block:
            return content[:s] + block + content[e:]
        before = content[:s].rstrip("\n")
        after = content[e:].lstrip("\n")
        out = before + "\n" if before else ""
        if after:
            out += ("\n" if before else "") + after
        return out
    if not block:
        return content
    if not ctx.user["exists"]:
        return NEW_FILE_HEADER + "\n" + block + "\n"
    if not content.strip():
        return block + "\n"
    return content.rstrip("\n") + "\n\n" + block + "\n"


# --------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------

def apply_records(ctx, records):
    """Rows = base rows overridden by records (records > hand-written > stock)."""
    rows = {rid: dict(row) for rid, row in ctx.base.items()}
    for rec in records:
        base = ctx.base.get(rec["id"])
        if base:
            default_key = base["key"] or base["origin_key"] or ""
            default_action = base["action"]
        else:
            default_key = ""
            default_action = ""
        row = _new_row(
            id=rec["id"], key=rec["key"], description=rec["description"], action=rec["action"],
            opts=rec.get("opts"), fn=rec.get("fn") or "o.bind",
            category=base["category"] if base else "Custom",
            source="managed", managed=True, default_key=default_key, default_action=default_action,
            stock_key=base["stock_key"] if base else "", origin_key=rec.get("origin_key"),
            last_key=rec.get("last_key"), file=base["file"] if base else None,
            is_mouse=_is_mouse(rec["key"] or rec.get("last_key") or "", rec.get("opts")),
            is_release=_is_release(rec.get("opts")),
        )
        if rec["key"] is None:
            row["status"] = "disabled"
        elif base is None:
            row["status"] = "custom"
        elif rec["key"] != default_key or rec["action"] != default_action:
            row["status"] = "modified"
        else:
            row["status"] = "default"
        rows[rec["id"]] = row
    return rows


def _compute_conflicts(rows):
    """Chords held by more than one row with a key. Mouse and release binds
    are exempt, as is a group that is entirely one stock file's own
    composite (e.g. the ALT + TAB pair in tiling.lua)."""
    groups = {}
    for r in rows.values():
        r["is_conflict"] = False
        r["conflict_with"] = []
        if not r["key"] or r["is_mouse"] or r["is_release"]:
            continue
        groups.setdefault(r["key"], []).append(r)
    conflicts = []
    for k, group in groups.items():
        if len(group) < 2:
            continue
        sources = {x["source"] for x in group}
        files = {x.get("file") for x in group}
        if sources == {"default"} and len(files) == 1 and files != {None}:
            continue
        for r in group:
            r["is_conflict"] = True
            r["conflict_with"] = [o["description"] for o in group if o is not r]
        conflicts.append({
            "key": k,
            "bindings": [
                {"id": x["id"], "description": x["description"], "action": x["action"],
                 "status": x["status"], "source": x["source"], "key": x["key"]}
                for x in group
            ],
        })
    return conflicts


def _public_row(r):
    return {k: v for k, v in r.items() if not k.startswith("_")}


def _load_all():
    ctx = load_context()
    records = load_records(ctx.block, ctx)
    rows = apply_records(ctx, records)
    _compute_conflicts(rows)
    return ctx, records, rows


def _trailing_region(content_without_block):
    """Line indices (into content_without_block.split('\\n')) of the trailing
    single-line, comment-free hl.unbind/o.bind statements that sit after the
    last hand-written statement -- what the old plugin appended."""
    lines = content_without_block.split("\n")
    i = len(lines) - 1
    region = []
    while i >= 0:
        s = lines[i].strip()
        if not s:
            i -= 1
            continue
        if _STMT_START_RE.match(s):
            code, comment = _scan_code(s)
            if not comment and _paren_depth(code) == 0 and parse_statement(code):
                region.append(i)
                i -= 1
                continue
        break
    return sorted(region), lines


def _content_without_block(ctx):
    if ctx.block_span:
        s, e = ctx.block_span
        return ctx.content[:s] + ctx.content[e:]
    return ctx.content


def build_complete_model():
    ctx, records, rows = _load_all()
    all_active = sorted(
        (_public_row(r) for r in rows.values()),
        key=lambda x: (x["description"].lower(), x["key"] or ""),
    )
    conflicts = _compute_conflicts(rows)
    for r in all_active:
        src = rows[r["id"]]
        r["is_conflict"] = src["is_conflict"]
        r["conflict_with"] = src["conflict_with"]
    by_desc = {}
    for r in all_active:
        by_desc.setdefault(r["description"].lower(), r)
    catalog = []
    for preset in PRESET_CATALOG:
        hit = by_desc.get(preset["name"].lower()) or by_desc.get(preset["description"].lower())
        cat_item = dict(preset)
        cat_item["is_bound"] = bool(hit and hit["key"])
        cat_item["current_key"] = (hit["key"] or "") if hit else ""
        cat_item["row_id"] = hit["id"] if hit else None
        catalog.append(cat_item)
    catalog.sort(key=lambda x: x.get("name", "").lower())
    region, _ = _trailing_region(_content_without_block(ctx))
    return {
        "active": all_active,
        "catalog": catalog,
        "conflicts": conflicts,
        "total_active": len([b for b in all_active if b["key"]]),
        "total_modified": len([b for b in all_active if b["status"] in ("modified", "custom")]),
        "total_conflicts": len(conflicts),
        "block_exists": ctx.block is not None,
        "pending_migration": len(region),
        "mouse_settings": get_mouse_scroll_settings(),
        "user_bindings_file": USER_BINDINGS_PATH,
    }


# --------------------------------------------------------------------------
# Write path: atomic write + reload + verify/rollback
# --------------------------------------------------------------------------

def reload_hyprland():
    code, reload_out, _ = run_cmd([HYPRCTL, "reload"])
    code2, cfg_out, _ = run_cmd([HYPRCTL, "configerrors"])
    return {
        "success": code == 0,
        "reload_output": (reload_out or "").strip(),
        "config_errors": (cfg_out or "").strip() if code2 == 0 else "",
    }


def _snapshot_bindings():
    """Capture (exists, raw_bytes, mode) of USER_BINDINGS_PATH for rollback, or
    None if the file is genuinely absent. Raises (fails closed) on unsafety."""
    try:
        src_fd, _ = safe_open_config(USER_BINDINGS_PATH, owner_check=True)
    except FileNotFoundError:
        return None
    try:
        raw = os.read(src_fd, MAX_FILE_BYTES + 1)
        if len(raw) > MAX_FILE_BYTES:
            raise ValueError("user bindings file exceeds size limit")
        return (True, raw, stat.S_IMODE(os.fstat(src_fd).st_mode))
    finally:
        os.close(src_fd)


def _restore_bindings(prior):
    """Atomically restore USER_BINDINGS_PATH to a prior _snapshot_bindings()
    result (exact bytes + mode). A prior of None removes the file if present."""
    if prior is None:
        name = Path(USER_BINDINGS_PATH).name
        parent_fd = _parent_dir_fd(USER_BINDINGS_PATH)
        try:
            try:
                os.unlink(name, dir_fd=parent_fd)
            except FileNotFoundError:
                pass
        finally:
            os.close(parent_fd)
        return
    _, raw, mode = prior
    _atomic_write(USER_BINDINGS_PATH, raw, mode)


def _verify_and_rollback(prior, key, old_key="", description=""):
    """After a write, reload Hyprland and validate. If reload fails or Hyprland
    reports config errors, atomically restore the exact prior file bytes + mode
    and reload again. The report is truthful about rollback: if restoration
    fails, the returned dict says so (rolled_back False) instead of claiming a
    rollback that did not happen."""
    status = reload_hyprland()
    if status.get("success") and not (status.get("config_errors") or "").strip():
        return status
    rollback_error = ""
    try:
        _restore_bindings(prior)
    except Exception as exc:  # noqa: BLE001 - surfaced, never swallowed
        rollback_error = str(exc)
    reload_hyprland()
    err = (status.get("config_errors") or "config validation failed").strip()
    if rollback_error:
        err = err + "; rollback FAILED: " + rollback_error
    else:
        err = err + "; changes rolled back"
    return {
        "success": False,
        "key": key,
        "old_key": old_key,
        "description": description,
        "reload": status,
        "rolled_back": not rollback_error,
        "error": err,
    }


def _write_user_file(content: str, mode):
    _atomic_write(USER_BINDINGS_PATH, content.encode("utf-8"), mode or 0o644)


def _commit(ctx, new_content, key="", description=""):
    if new_content == ctx.content:
        return {"success": True, "changed": False, "key": key, "reload": None, "error": None}
    prior = _snapshot_bindings()
    _write_user_file(new_content, ctx.mode)
    status = _verify_and_rollback(prior, key, "", description)
    ok = bool(status.get("success", False))
    return {
        "success": ok,
        "changed": True,
        "key": key,
        "reload": status if ok else status.get("reload"),
        "rolled_back": status.get("rolled_back"),
        "error": status.get("error"),
    }


# --------------------------------------------------------------------------
# Operations
# --------------------------------------------------------------------------

def _resolve_row(rows, token, rec_id=None, default_key=""):
    """Find the row an operation targets: explicit --id, else a description
    match, else the chord (managed rows and press binds preferred; disabled
    rows also match on the chord they had)."""
    if rec_id:
        return rows.get(_make_id(rec_id)) or rows.get(rec_id)
    tid = _make_id(token)
    if tid in rows:
        return rows[tid]
    nk = normalize_key_chord(token)
    if not nk:
        return None
    cands = [r for r in rows.values() if r["key"] == nk]
    if not cands:
        cands = [r for r in rows.values() if not r["key"] and nk in (r["last_key"], r["default_key"], r["stock_key"])]
    if not cands:
        return None
    ndef = normalize_key_chord(default_key) if default_key else ""
    cands.sort(key=lambda r: (not r["managed"], r["is_release"], ndef and r["default_key"] != ndef, r["id"]))
    return cands[0]


def _resolve_set_id(rows, description, old_key="", rec_id=None):
    if rec_id:
        return _make_id(rec_id) if _make_id(rec_id) in rows else rec_id
    did = _make_id(description)
    if did in rows:
        return did
    nok = normalize_key_chord(old_key) if old_key else ""
    if nok:
        cands = [r for r in rows.values() if r["key"] == nok]
        if len(cands) == 1:
            return cands[0]["id"]
    return did


def _locked_info(row):
    if row and row["source"] == "user-file" and not row["managed"]:
        return {"file_line": row["file_line"],
                "reason": "hand-written in bindings.lua; the plugin never edits it, an edit shadows it from the managed block"}
    return None


def _diff_blocks(old_block, new_block):
    skip = {BLOCK_START, BLOCK_END, BLOCK_HEADER}
    old_lines = [l for l in (old_block or "").split("\n") if l.strip() and l not in skip]
    new_lines = [l for l in (new_block or "").split("\n") if l.strip() and l not in skip]
    old_set, new_set = set(old_lines), set(new_lines)
    added = [l for l in new_lines if l not in old_set]
    would_unbind = []
    would_write = []
    for l in added:
        m = _UNBIND_RE.match(l)
        (would_unbind if m else would_write).append(m.group(1) if m else l)
    would_remove = [l for l in old_lines if l not in new_set]
    return would_unbind, would_write, would_remove


def _plan_set(ctx, records, rows, rid, norm_key, description, lua_action, displace, opts_override=None):
    existing = next((r for r in records if r["id"] == rid), None)
    base = ctx.base.get(rid)
    row = rows.get(rid)
    holders = [r for r in rows.values() if r["key"] == norm_key and r["id"] != rid]
    conflict = holders[0] if holders else None
    opts = opts_override if opts_override is not None else ((existing or row or {}).get("opts"))
    fn = (existing or row or {}).get("fn") or "o.bind"
    plan = {"conflict": _public_row(conflict) if conflict else None, "displaced": None,
            "displaced_all": [], "would_unbind": [], "would_write": [], "would_remove": [],
            "changed": False, "records": records, "block": ctx.block, "id": rid}
    if holders and not displace:
        return plan
    new_records = [dict(r) for r in records if r["id"] != rid]
    for h in holders:
        rec = next((r for r in new_records if r["id"] == h["id"]), None)
        if rec:
            rec["last_key"] = rec["key"]
            rec["key"] = None
        else:
            new_records.append({
                "id": h["id"], "description": h["description"], "key": None, "last_key": h["key"],
                "action": h["action"], "opts": h["opts"], "fn": h["fn"], "origin_key": h["key"],
            })
    # Exactly the state the identity has outside the block: no record needed
    # (and an existing one is dropped).
    identical_to_base = (
        not holders and base is not None and base["key"] == norm_key
        and base["action"] == lua_action and base["description"] == description
        and (base.get("opts") or None) == (opts or None)
    )
    if not identical_to_base:
        new_records.append({
            "id": rid, "description": description, "key": norm_key, "last_key": None,
            "action": lua_action, "opts": opts, "fn": fn, "origin_key": ctx.origin_for(rid),
        })
    new_block = render_block(new_records, ctx) if new_records else ""
    plan["records"] = new_records
    plan["block"] = new_block
    plan["changed"] = new_block != (ctx.block or "")
    plan["would_unbind"], plan["would_write"], plan["would_remove"] = _diff_blocks(ctx.block, new_block)
    if holders:
        new_rows = apply_records(ctx, new_records)
        _compute_conflicts(new_rows)
        plan["displaced_all"] = [_public_row(new_rows[h["id"]]) for h in holders]
        plan["displaced"] = plan["displaced_all"][0]
    return plan


def _validate_set_inputs(key, description, command, action):
    norm_key = normalize_key_chord(key)
    if not norm_key:
        return None, {"success": False, "error": "Invalid key combination", "key": key}
    if not (description or "").strip():
        return None, {"success": False, "error": "Description is required", "key": norm_key}
    if len(description or "") > MAX_TEXT_LEN or len(command or "") > MAX_CMD_LEN or len(action or "") > MAX_CMD_LEN:
        return None, {"success": False, "error": "Description or command exceeds allowed length", "key": norm_key}
    return norm_key, None


def check_keybinding(key, description, command="", action="", old_key="", rec_id=None, displace=False):
    """Pure: what `set` with the same arguments would do. No write."""
    norm_key, err = _validate_set_inputs(key, description, command, action)
    if err:
        return err
    ctx, records, rows = _load_all()
    rid = _resolve_set_id(rows, description, old_key, rec_id)
    row = rows.get(rid)
    if command or action:
        lua_action = _build_action(command, action)
    else:
        lua_action = row["action"] if row else '""'
    plan = _plan_set(ctx, records, rows, rid, norm_key, description.strip(), lua_action, displace)
    return {
        "key": norm_key,
        "id": rid,
        "conflict": plan["conflict"],
        "displaced": plan["displaced"],
        "displaced_all": plan["displaced_all"],
        "would_unbind": plan["would_unbind"],
        "would_write": plan["would_write"],
        "would_remove": plan["would_remove"],
        "changed": plan["changed"],
        "locked": _locked_info(row),
    }


def set_keybinding(key, description, command, action="", old_key="", rec_id=None, displace=False,
                   override_conflicts=None):
    norm_key, err = _validate_set_inputs(key, description, command, action)
    if err:
        return err
    description = description.strip()
    ctx, records, rows = _load_all()
    rid = _resolve_set_id(rows, description, old_key, rec_id)
    lua_action = _build_action(command, action)
    plan = _plan_set(ctx, records, rows, rid, norm_key, description, lua_action, displace)
    if plan["conflict"] and not displace:
        return {
            "success": False, "key": norm_key, "id": rid, "conflict": plan["conflict"],
            "displaced": None, "reload": None,
            "error": f"{norm_key} is held by {plan['conflict']['description']}",
        }
    if not plan["changed"]:
        return {"success": True, "changed": False, "key": norm_key, "id": rid, "displaced": None,
                "reload": None, "error": None}
    res = _commit(ctx, render_file(ctx, plan["records"]), norm_key, description)
    res.update({"id": rid, "displaced": plan["displaced"], "displaced_all": plan["displaced_all"],
                "old_key": normalize_key_chord(old_key) if old_key else ""})
    return res


def _still_unbound_by(records, ctx, chord, exclude_id):
    """The record (other than exclude_id) whose rendering keeps `chord`
    unbound, or None."""
    for r in records:
        if r["id"] == exclude_id:
            continue
        if r["key"] is None and r.get("origin_key") == chord:
            return r
        if r["key"] and r.get("origin_key") == chord and r["key"] != chord:
            return r
    return None


def _refuse(row_id, chord, other_row, reason):
    return {"success": False, "key": chord, "id": row_id, "conflict": _public_row(other_row) if other_row else None,
            "reload": None, "error": reason}


def reset_keybinding(key, default_key="", rec_id=None):
    ctx, records, rows = _load_all()
    row = _resolve_row(rows, key, rec_id, default_key)
    if row is None:
        return {"success": False, "error": f"No binding matches {key}", "key": key, "reload": None}
    rec = next((r for r in records if r["id"] == row["id"]), None)
    if rec is None:
        locked = _locked_info(row)
        if locked:
            return {"success": False, "key": row["key"], "id": row["id"], "locked": locked, "reload": None,
                    "error": f"'{row['description']}' is hand-written in bindings.lua (line {locked['file_line']}); edit the file to change it"}
        return {"success": True, "changed": False, "key": row["key"], "id": row["id"], "reload": None, "error": None}
    new_records = [r for r in records if r["id"] != row["id"]]
    base = ctx.base.get(row["id"])
    if base and base["key"]:
        new_rows = apply_records(ctx, new_records)
        holders = [r for r in new_rows.values() if r["key"] == base["key"] and r["id"] != row["id"]]
        if holders:
            return _refuse(row["id"], base["key"], holders[0],
                           f"{base['key']} is held by {holders[0]['description']}")
        other = _still_unbound_by(new_records, ctx, base["key"], row["id"])
        if other:
            return _refuse(row["id"], base["key"], new_rows.get(other["id"]),
                           f"{base['key']} stays unbound: '{other['description']}' was moved off it")
    res = _commit(ctx, render_file(ctx, new_records), base["key"] if base else (row["key"] or ""), row["description"])
    res.update({"id": row["id"], "deleted": base is None})
    return res


def disable_keybinding(key, rec_id=None):
    ctx, records, rows = _load_all()
    row = _resolve_row(rows, key, rec_id)
    if row is None:
        return {"success": False, "error": f"No binding matches {key}", "key": key, "reload": None}
    if not row["key"]:
        return {"success": True, "changed": False, "key": None, "id": row["id"], "reload": None, "error": None}
    new_records = [dict(r) for r in records]
    rec = next((r for r in new_records if r["id"] == row["id"]), None)
    if rec:
        rec["last_key"] = rec["key"]
        rec["key"] = None
    else:
        new_records.append({
            "id": row["id"], "description": row["description"], "key": None, "last_key": row["key"],
            "action": row["action"], "opts": row["opts"], "fn": row["fn"], "origin_key": row["key"],
        })
    res = _commit(ctx, render_file(ctx, new_records), row["key"], row["description"])
    res.update({"id": row["id"]})
    return res


def enable_keybinding(key, rec_id=None):
    ctx, records, rows = _load_all()
    row = _resolve_row(rows, key, rec_id)
    if row is None:
        return {"success": False, "error": f"No binding matches {key}", "key": key, "reload": None}
    if row["key"]:
        return {"success": True, "changed": False, "key": row["key"], "id": row["id"], "reload": None, "error": None}
    rec = next((r for r in records if r["id"] == row["id"]), None)
    if rec is None:
        locked = _locked_info(row)
        return {"success": False, "key": None, "id": row["id"], "locked": locked, "reload": None,
                "error": f"'{row['description']}' is disabled by a hand-written hl.unbind in bindings.lua"
                         + (f" (line {locked['file_line']})" if locked else "")}
    base = ctx.base.get(row["id"])
    if base is not None:
        # Stock or hand-written identity: dropping the record restores it.
        target = base["key"]
        new_records = [r for r in records if r["id"] != row["id"]]
        if not target:
            locked = _locked_info(base)
            return {"success": False, "key": None, "id": row["id"], "locked": locked, "reload": None,
                    "error": f"'{row['description']}' has no binding to return to outside the managed block"}
    else:
        target = rec.get("last_key")
        if not target:
            return {"success": False, "key": None, "id": row["id"], "reload": None,
                    "error": f"'{row['description']}' has no remembered key to restore"}
        new_records = [dict(r) for r in records]
        for r in new_records:
            if r["id"] == row["id"]:
                r["key"] = target
                r["last_key"] = None
    new_rows = apply_records(ctx, new_records)
    holders = [r for r in new_rows.values() if r["key"] == target and r["id"] != row["id"]]
    if holders:
        return _refuse(row["id"], target, holders[0], f"{target} is held by {holders[0]['description']}")
    if base is not None:
        other = _still_unbound_by(new_records, ctx, target, row["id"])
        if other:
            return _refuse(row["id"], target, new_rows.get(other["id"]),
                           f"{target} stays unbound: '{other['description']}' was moved off it")
    res = _commit(ctx, render_file(ctx, new_records), target, row["description"])
    res.update({"id": row["id"]})
    return res


def migrate_trailing():
    """Move the trailing hl.unbind/o.bind lines the old plugin appended after
    the last hand-written statement (outside any marked block) into the
    managed block. Idempotent; touches nothing else."""
    ctx = load_context()
    without = _content_without_block(ctx)
    region, lines = _trailing_region(without)
    if not region:
        return {"success": True, "migrated": 0, "changed": False, "records": [], "reload": None, "error": None}
    region_set = set(region)
    # Rebuild the context as if those lines were not hand-written.
    user2 = dict(ctx.user)
    user2["binds"] = [b for b in ctx.user["binds"] if (b["line"] - 1) not in region_set]
    user2["unbinds"] = [u for u in ctx.user["unbinds"] if (u["line"] - 1) not in region_set]
    ctx2 = Context(ctx.stock, user2)
    stmts = [{"line": i + 1, "code": _scan_code(lines[i].strip())[0], "comment": "", "disabled": False} for i in region]
    migrated = _records_from_statements(stmts, ctx2)
    existing = load_records(ctx.block, ctx2)
    existing_ids = {r["id"] for r in existing}
    merged = existing + [r for r in migrated if r["id"] not in existing_ids]
    kept = [l for i, l in enumerate(lines) if i not in region_set]
    body = "\n".join(kept).rstrip("\n")
    if merged:
        new_content = (body + "\n\n" if body else NEW_FILE_HEADER + "\n") + render_block(merged, ctx2) + "\n"
    else:
        new_content = body + "\n" if body else ""
    res = _commit(ctx, new_content, "", "migrate")
    res.update({"migrated": len(region), "records": [r["id"] for r in migrated]})
    return res


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

USAGE = {
    "set": "Usage: set <key> <desc> <command> [action] [old_key] [--id ID] [--displace]",
    "check": "Usage: check <key> <desc> [--id ID] [--old-key K] [--cmd C] [--action A] [--displace]",
    "reset": "Usage: reset <key|desc> [default_key] [--id ID]",
    "disable": "Usage: disable <key|desc> [--id ID]",
    "enable": "Usage: enable <key|desc> [--id ID]",
}


def _parse_argv(argv):
    """Positionals in order, plus --id/--old-key/--cmd/--action values and the
    --displace flag. Positional forms stay backward compatible."""
    pos = []
    flags = {"id": None, "old_key": "", "cmd": None, "action": None, "displace": False}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--displace":
            flags["displace"] = True
        elif a in ("--id", "--old-key", "--cmd", "--action"):
            if i + 1 >= len(argv):
                raise ValueError(f"{a} needs a value")
            flags[a[2:].replace("-", "_")] = argv[i + 1]
            i += 1
        elif a.startswith("--id=") or a.startswith("--old-key=") or a.startswith("--cmd=") or a.startswith("--action="):
            k, v = a[2:].split("=", 1)
            flags[k.replace("-", "_")] = v
        else:
            pos.append(a)
        i += 1
    return pos, flags


def main():
    argv = sys.argv[1:]
    if not argv:
        print(json.dumps(build_complete_model(), indent=2))
        return
    cmd = argv[0]
    try:
        pos, flags = _parse_argv(argv[1:])
    except ValueError as exc:
        print(json.dumps({"success": False, "error": str(exc)}))
        sys.exit(1)
    if cmd == "list":
        print(json.dumps(build_complete_model()))
    elif cmd == "check":
        if len(pos) < 2:
            print(json.dumps({"success": False, "error": USAGE["check"]}))
            sys.exit(1)
        res = check_keybinding(pos[0], pos[1], command=flags["cmd"] or "", action=flags["action"] or "",
                               old_key=flags["old_key"], rec_id=flags["id"], displace=flags["displace"])
        print(json.dumps(res))
    elif cmd == "set":
        if len(pos) < 3:
            print(json.dumps({"success": False, "error": USAGE["set"]}))
            sys.exit(1)
        action = pos[3] if len(pos) > 3 else ""
        old_key = pos[4] if len(pos) > 4 else flags["old_key"]
        res = set_keybinding(pos[0], pos[1], pos[2], action, old_key, rec_id=flags["id"], displace=flags["displace"])
        print(json.dumps(res))
    elif cmd == "reset":
        if len(pos) < 1:
            print(json.dumps({"success": False, "error": USAGE["reset"]}))
            sys.exit(1)
        res = reset_keybinding(pos[0], pos[1] if len(pos) > 1 else "", rec_id=flags["id"])
        print(json.dumps(res))
    elif cmd == "disable":
        if len(pos) < 1:
            print(json.dumps({"success": False, "error": USAGE["disable"]}))
            sys.exit(1)
        print(json.dumps(disable_keybinding(pos[0], rec_id=flags["id"])))
    elif cmd == "enable":
        if len(pos) < 1:
            print(json.dumps({"success": False, "error": USAGE["enable"]}))
            sys.exit(1)
        print(json.dumps(enable_keybinding(pos[0], rec_id=flags["id"])))
    elif cmd == "migrate":
        print(json.dumps(migrate_trailing()))
    elif cmd == "reload":
        print(json.dumps(reload_hyprland()))
    else:
        print(json.dumps({"success": False, "error": f"Unknown command {cmd}. Commands: list, check, set, reset, disable, enable, migrate, reload"}))
        sys.exit(1)


if __name__ == "__main__":
    main()
